name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install OpenSCAD nightly
      # You may pin to the exact commit or the version.
      # uses: Irev-Dev/action-install-openscad-nightly@24e2fa85f1f791bd4a8b0ee36fa2603416fae262
      uses: Irev-Dev/action-install-openscad-nightly@v0.0.1

    - name: Build
      run: make
