name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install OpenSCAD
      run: sudo apt update && sudo apt install openscad
    - name: Build
      run: make clean && make all
